name: {{cookiecutter.__project_slug}}
channels:
  - defaults
  - conda-forge
dependencies:
  - black
  - flake8
  - isort
  - mypy
  - pytest
  - pytest-cov
  - python={{cookiecutter.python_version}}
  - python-dotenv
