name: {{cookiecutter.project_name}}
channels:
  - defaults
dependencies:
  - isort
  - pycodestyle
  - pylint
  - pytest
  - pytest-cov
  - python={{cookiecutter.python_version}}
  - pip:
    - black
